---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-demo
  namespace: ecoent-gcent-gcent
  labels:
    app: news-demo
spec:
  selector:
    matchLabels:
      app: news-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: news-demo
    spec:
      containers:
        - name: news-demo
          image: image-registry.openshift-image-registry.svc:5000/eco-gcdevgroup1-private/news-demo:v0.1
          ports:
            - containerPort: 3000
          env:
          - name: NEWS_API_KEY
            valueFrom:
              configMapKeyRef:
                name: news-demo
                key: NEWS_API_KEY

